[build]
  command = "npm run build"
  publish = "dist/zakkerni-app/browser"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Disable Angular Universal for problematic routes
[[redirects]]
  from = "/tasks"
  to = "/tasks"
  status = 200
  force = false