[build]
  command = "ng build --configuration production --output-path=dist"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# منع Angular SSR تماماً
[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200